FROM python:3.11-slim

# cartella di lavoro nel container
WORKDIR /repository4

# copia requirements
COPY repository4/requirements.txt .

# installa dipendenze
RUN pip install --no-cache-dir -r requirements.txt

# copia il codice
COPY repository4/ .

# comando di avvio
CMD ["python", "main.py"]