version: "3.9"

services:
  app:
    build: .
    container_name: app_livescore
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
    restart: always

  mongo:
    image: mongo:7
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: